language: java

services:
  - mongodb

install:
  # Install Indri
  - wget --content-disposition http://sourceforge.net/projects/lemur/files/lemur/indri-5.9/indri-5.9.tar.gz/download
  - tar -xzvf indri-5.9.tar.gz
  - cd indri-5.9 && chmod +x configure && ./configure --prefix=$HOME/indri --enable-java --with-javahome=$JAVA_HOME && make && make install
  
cache:
  apt: true
  maven: true
  directories:
  - '$HOME/indri'
  - '$HOME/.m2/repository'
