language: java

sudo: required

install:
  # Install Ansible.
  - sudo pip install ansible

script:
  # Install dependencies for integration testing
  - sudo ansible-playbook -i "localhost," -c local playbook.yml