language: java

addons:
  apt:
    packages:
    - mongodb

install:
  # Install Indri
  - wget 'http://downloads.sourceforge.net/project/lemur/lemur/indri-5.9/indri-5.9.tar.gz'
  - tar -xzvf indri-5.9.tar.gz
  - cd indri-5.9 && chmod +x configure && ./configure --prefix=$HOME/indri --enable-java --with-javahome=/usr/lib/jvm/java-7-oracle && make && make install
  
cache:
  directories:
  - $HOME/indri
